// Single source of truth for Navi skin artwork.
//
// The app used to offer two render modes — hand-written SVG sprite components
// and AI-generated PNGs — toggled per page. That is gone: there is now one
// look, the stylized 3D CGI render, generated by the navi-generate-skin edge
// function into the `cgi/` folder of the navi-skins bucket.
//
// Note the `cgi/` prefix. The old flat `<name>.png` objects are the original
// DALL·E art on solid white plates, which looked wrong against a dark theme.
// They are deliberately left in place (untouched, not deleted) so nothing is
// lost, but nothing reads from them any more.
const BASE = `${import.meta.env.VITE_SUPABASE_URL}/storage/v1/object/public/navi-skins/cgi`;

/** Public URL for a skin's artwork, keyed by its display name (e.g. "Flamebird"). */
export function skinArtUrl(skinName: string | null | undefined): string {
  return `${BASE}/${String(skinName ?? "").toLowerCase()}.png`;
}
