import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const EFFECTIVE_DATE = "August 3, 2026";
const CONTACT_EMAIL = "support@navi.exe";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="font-display text-sm font-bold text-primary tracking-widest">{title}</h2>
      <div className="text-sm font-body text-foreground/90 leading-relaxed space-y-2">{children}</div>
    </section>
  );
}

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-2xl mx-auto px-6 py-10">
        <Link to="/" className="inline-flex items-center gap-1.5 text-xs font-mono text-muted-foreground hover:text-primary transition-colors mb-8">
          <ArrowLeft size={12} /> BACK TO NAVI.EXE
        </Link>

        <h1 className="text-2xl font-display font-bold text-primary tracking-wider text-glow-cyan mb-1">
          TERMS OF SERVICE
        </h1>
        <p className="text-xs font-mono text-muted-foreground mb-8">Effective {EFFECTIVE_DATE}</p>

        <div className="space-y-8">
          <Section title="1. ACCEPTANCE OF TERMS">
            <p>
              By creating an account or using NAVI.EXE ("the app", "the service"), you agree to
              these Terms of Service. If you don't agree, don't use the app.
            </p>
          </Section>

          <Section title="2. ELIGIBILITY">
            <p>
              You must be at least 13 years old to use NAVI.EXE. By using the app, you represent
              that you meet this requirement and that any information you provide is accurate.
            </p>
          </Section>

          <Section title="3. YOUR ACCOUNT">
            <p>
              You're responsible for maintaining the confidentiality of your login credentials and
              for all activity under your account. Let us know immediately if you suspect
              unauthorized access.
            </p>
          </Section>

          <Section title="4. SUBSCRIPTIONS & PAYMENTS">
            <p>
              NAVI.EXE offers optional paid subscription tiers. Subscriptions are billed in advance
              on a recurring basis (monthly or annual, depending on your selection) through Stripe.
              You can cancel anytime from the billing portal in the Upgrade page — your access
              continues until the end of the current billing period. Except where required by law,
              payments are non-refundable.
            </p>
          </Section>

          <Section title="5. AI COMPANION & CONTENT">
            <p>
              Your NAVI companion's responses are generated by AI and may occasionally be
              inaccurate, incomplete, or not reflect our views. Don't rely on NAVI for medical,
              legal, financial, or emergency advice. Conversations with your NAVI companion are
              processed by third-party AI providers as described in our Privacy Policy.
            </p>
          </Section>

          <Section title="6. USER CONDUCT">
            <p>By using social features (the Feed, guilds, direct messages), you agree not to:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li>Harass, threaten, or abuse other users</li>
              <li>Post illegal, hateful, or sexually explicit content</li>
              <li>Impersonate another person or entity</li>
              <li>Attempt to exploit, hack, or disrupt the service</li>
              <li>Use the app for any unlawful purpose</li>
            </ul>
            <p>
              We may remove content or suspend accounts that violate these terms, at our
              discretion, using the in-app reporting tools or our own review.
            </p>
          </Section>

          <Section title="7. VIRTUAL ITEMS & CURRENCY">
            <p>
              Codex Points, Cali Coins, skins, and other in-app items have no real-world monetary
              value, cannot be exchanged for cash, and are non-transferable between accounts. We
              may adjust, reset, or discontinue virtual items at our discretion.
            </p>
          </Section>

          <Section title="8. INTELLECTUAL PROPERTY">
            <p>
              NAVI.EXE, its design, and its content (excluding content you submit) are owned by us
              or our licensors. You retain ownership of content you post, but grant us a license to
              store, display, and process it as needed to operate the service.
            </p>
          </Section>

          <Section title="9. TERMINATION">
            <p>
              You may stop using NAVI.EXE and request account deletion at any time by contacting{" "}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary hover:underline">{CONTACT_EMAIL}</a>.
              We may suspend or terminate accounts that violate these terms.
            </p>
          </Section>

          <Section title="10. DISCLAIMER OF WARRANTIES">
            <p>
              NAVI.EXE is provided "as is" without warranties of any kind, express or implied. We
              don't guarantee the service will be uninterrupted, error-free, or that AI-generated
              content will be accurate.
            </p>
          </Section>

          <Section title="11. LIMITATION OF LIABILITY">
            <p>
              To the fullest extent permitted by law, we are not liable for any indirect,
              incidental, or consequential damages arising from your use of NAVI.EXE.
            </p>
          </Section>

          <Section title="12. CHANGES TO THESE TERMS">
            <p>
              We may update these terms from time to time. We'll update the effective date above
              when we do. Continued use after changes take effect constitutes acceptance.
            </p>
          </Section>

          <Section title="13. CONTACT">
            <p>
              Questions about these terms? Reach us at{" "}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary hover:underline">{CONTACT_EMAIL}</a>.
            </p>
          </Section>
        </div>
      </div>
    </div>
  );
}
