-- ============================================================
-- NAVI COMPANION CHATTER — friends'/party's/guild's NAVIs "hang
-- out" amongst themselves (Mega Man NT Warrior-style), operators
-- can only read the transcript, never post into it themselves.
-- Generated by navi-agent-runner's internal run_companion_chatter
-- action, invoked periodically by the cron job below — mirrors the
-- net.http_post + Vault pattern already used by navi-daily-reminders
-- (20260803020000_push_notifications.sql).
-- ============================================================

CREATE TABLE IF NOT EXISTS public.navi_companion_threads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  context_type text NOT NULL CHECK (context_type IN ('friend', 'party', 'guild')),
  context_id uuid, -- party_id/guild_id for those contexts, NULL for friend pairs
  participant_ids uuid[] NOT NULL,
  created_at timestamptz DEFAULT now(),
  last_message_at timestamptz DEFAULT now()
);

-- One thread per friend pair, one per party, one per guild (guild sessions
-- rotate which members are sampled in, but the thread itself is per-guild).
CREATE UNIQUE INDEX IF NOT EXISTS navi_companion_threads_friend_pair
  ON public.navi_companion_threads (participant_ids) WHERE context_type = 'friend';
CREATE UNIQUE INDEX IF NOT EXISTS navi_companion_threads_context
  ON public.navi_companion_threads (context_type, context_id) WHERE context_type IN ('party', 'guild');

ALTER TABLE public.navi_companion_threads ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "navi_companion_threads_participant_read" ON public.navi_companion_threads;
CREATE POLICY "navi_companion_threads_participant_read" ON public.navi_companion_threads
  FOR SELECT USING (auth.uid() = ANY(participant_ids));
-- No INSERT/UPDATE/DELETE policy for regular users — only the service-role
-- client (cron -> navi-agent-runner) writes here.

CREATE TABLE IF NOT EXISTS public.navi_companion_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id uuid REFERENCES public.navi_companion_threads(id) ON DELETE CASCADE NOT NULL,
  speaker_user_id uuid NOT NULL,
  speaker_navi_name text NOT NULL,
  content text NOT NULL,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS navi_companion_messages_thread_idx ON public.navi_companion_messages (thread_id, created_at);

ALTER TABLE public.navi_companion_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "navi_companion_messages_participant_read" ON public.navi_companion_messages;
CREATE POLICY "navi_companion_messages_participant_read" ON public.navi_companion_messages
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.navi_companion_threads t
      WHERE t.id = thread_id AND auth.uid() = ANY(t.participant_ids)
    )
  );

SELECT cron.unschedule('navi-companion-chatter') WHERE EXISTS (
  SELECT 1 FROM cron.job WHERE jobname = 'navi-companion-chatter'
);

-- Every 4 hours — each run only advances groups past their own 6h cooldown
-- and caps itself at 8 groups, so more frequent ticks just mean shorter
-- real-world lag before a newly-formed friend/party/guild connection gets
-- its first exchange, not runaway generation volume.
SELECT cron.schedule(
  'navi-companion-chatter',
  '0 */4 * * *',
  $$
  SELECT net.http_post(
    url     := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'supabase_url') || '/functions/v1/navi-agent-runner',
    headers := jsonb_build_object(
                 'Content-Type', 'application/json',
                 'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'service_role_key')
               ),
    body    := '{"action":"run_companion_chatter"}'::jsonb,
    timeout_milliseconds := 60000
  ) AS request_id;
  $$
);
