ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS perception integer NOT NULL DEFAULT 10,
ADD COLUMN IF NOT EXISTS luck integer NOT NULL DEFAULT 10,
ADD COLUMN IF NOT EXISTS codex_points integer NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS cali_coins integer NOT NULL DEFAULT 0;